window.gameData = window.gameData || {};
window.gameData.countries = [
    // América del Sur
    { name: "Argentina", code: "ar", continent: "América del Sur" },
    { name: "Bolivia", code: "bo", continent: "América del Sur" },
    { name: "Brasil", code: "br", continent: "América del Sur" },
    { name: "Chile", code: "cl", continent: "América del Sur" },
    { name: "Colombia", code: "co", continent: "América del Sur" },
    { name: "Ecuador", code: "ec", continent: "América del Sur" },
    { name: "Guyana", code: "gy", continent: "América del Sur" },
    { name: "Paraguay", code: "py", continent: "América del Sur" },
    { name: "Perú", code: "pe", continent: "América del Sur" },
    { name: "Surinam", code: "sr", continent: "América del Sur" },
    { name: "Uruguay", code: "uy", continent: "América del Sur" },
    { name: "Venezuela", code: "ve", continent: "América del Sur" },

    // América del Norte (incluye Central y Caribe)
    { name: "Estados Unidos", code: "us", continent: "América del Norte" },
    { name: "Canadá", code: "ca", continent: "América del Norte" },
    { name: "México", code: "mx", continent: "América del Norte" },
    { name: "Antigua y Barbuda", code: "ag", continent: "América del Norte" },
    { name: "Bahamas", code: "bs", continent: "América del Norte" },
    { name: "Barbados", code: "bb", continent: "América del Norte" },
    { name: "Belice", code: "bz", continent: "América del Norte" },
    { name: "Costa Rica", code: "cr", continent: "América del Norte" },
    { name: "Cuba", code: "cu", continent: "América del Norte" },
    { name: "Dominica", code: "dm", continent: "América del Norte" },
    { name: "República Dominicana", code: "do", continent: "América del Norte" },
    { name: "El Salvador", code: "sv", continent: "América del Norte" },
    { name: "Granada", code: "gd", continent: "América del Norte" },
    { name: "Guatemala", code: "gt", continent: "América del Norte" },
    { name: "Haití", code: "ht", continent: "América del Norte" },
    { name: "Honduras", code: "hn", continent: "América del Norte" },
    { name: "Jamaica", code: "jm", continent: "América del Norte" },
    { name: "Nicaragua", code: "ni", continent: "América del Norte" },
    { name: "Panamá", code: "pa", continent: "América del Norte" },
    { name: "San Cristóbal y Nieves", code: "kn", continent: "América del Norte" },
    { name: "Santa Lucía", code: "lc", continent: "América del Norte" },
    { name: "San Vicente y las Granadinas", code: "vc", continent: "América del Norte" },
    { name: "Trinidad y Tobago", code: "tt", continent: "América del Norte" },

    // Europa
    { name: "Albania", code: "al", continent: "Europa" },
    { name: "Andorra", code: "ad", continent: "Europa" },
    { name: "Armenia", code: "am", continent: "Europa" },
    { name: "Austria", code: "at", continent: "Europa" },
    { name: "Bielorrusia", code: "by", continent: "Europa" },
    { name: "Bélgica", code: "be", continent: "Europa" },
    { name: "Bosnia y Herzegovina", code: "ba", continent: "Europa" },
    { name: "Bulgaria", code: "bg", continent: "Europa" },
    { name: "Croacia", code: "hr", continent: "Europa" },
    { name: "Chipre", code: "cy", continent: "Europa" },
    { name: "República Checa", code: "cz", continent: "Europa" },
    { name: "Dinamarca", code: "dk", continent: "Europa" },
    { name: "Estonia", code: "ee", continent: "Europa" },
    { name: "Finlandia", code: "fi", continent: "Europa" },
    { name: "Francia", code: "fr", continent: "Europa" },
    { name: "Georgia", code: "ge", continent: "Europa" },
    { name: "Alemania", code: "de", continent: "Europa" },
    { name: "Grecia", code: "gr", continent: "Europa" },
    { name: "Hungría", code: "hu", continent: "Europa" },
    { name: "Islandia", code: "is", continent: "Europa" },
    { name: "Irlanda", code: "ie", continent: "Europa" },
    { name: "Italia", code: "it", continent: "Europa" },
    { name: "Kosovo", code: "xk", continent: "Europa" },
    { name: "Letonia", code: "lv", continent: "Europa" },
    { name: "Liechtenstein", code: "li", continent: "Europa" },
    { name: "Lituania", code: "lt", continent: "Europa" },
    { name: "Luxemburgo", code: "lu", continent: "Europa" },
    { name: "Malta", code: "mt", continent: "Europa" },
    { name: "Moldavia", code: "md", continent: "Europa" },
    { name: "Mónaco", code: "mc", continent: "Europa" },
    { name: "Montenegro", code: "me", continent: "Europa" },
    { name: "Países Bajos", code: "nl", continent: "Europa" },
    { name: "Macedonia del Norte", code: "mk", continent: "Europa" },
    { name: "Noruega", code: "no", continent: "Europa" },
    { name: "Polonia", code: "pl", continent: "Europa" },
    { name: "Portugal", code: "pt", continent: "Europa" },
    { name: "Rumania", code: "ro", continent: "Europa" },
    { name: "Rusia", code: "ru", continent: "Europa" },
    { name: "San Marino", code: "sm", continent: "Europa" },
    { name: "Serbia", code: "rs", continent: "Europa" },
    { name: "Eslovaquia", code: "sk", continent: "Europa" },
    { name: "Eslovenia", code: "si", continent: "Europa" },
    { name: "España", code: "es", continent: "Europa" },
    { name: "Suecia", code: "se", continent: "Europa" },
    { name: "Suiza", code: "ch", continent: "Europa" },
    { name: "Ucrania", code: "ua", continent: "Europa" },
    { name: "Reino Unido", code: "gb", continent: "Europa" },
    { name: "Ciudad del Vaticano", code: "va", continent: "Europa" },

    // Asia
    { name: "Afganistán", code: "af", continent: "Asia" },
    { name: "Azerbaiyán", code: "az", continent: "Asia" },
    { name: "Baréin", code: "bh", continent: "Asia" },
    { name: "Bangladesh", code: "bd", continent: "Asia" },
    { name: "Bután", code: "bt", continent: "Asia" },
    { name: "Brunéi", code: "bn", continent: "Asia" },
    { name: "Camboya", code: "kh", continent: "Asia" },
    { name: "China", code: "cn", continent: "Asia" },
    { name: "Timor Oriental", code: "tl", continent: "Asia" },
    { name: "India", code: "in", continent: "Asia" },
    { name: "Indonesia", code: "id", continent: "Asia" },
    { name: "Irán", code: "ir", continent: "Asia" },
    { name: "Irak", code: "iq", continent: "Asia" },
    { name: "Israel", code: "il", continent: "Asia" },
    { name: "Japón", code: "jp", continent: "Asia" },
    { name: "Jordania", code: "jo", continent: "Asia" },
    { name: "Kazajistán", code: "kz", continent: "Asia" },
    { name: "Kuwait", code: "kw", continent: "Asia" },
    { name: "Kirguistán", code: "kg", continent: "Asia" },
    { name: "Laos", code: "la", continent: "Asia" },
    { name: "Líbano", code: "lb", continent: "Asia" },
    { name: "Malasia", code: "my", continent: "Asia" },
    { name: "Maldivas", code: "mv", continent: "Asia" },
    { name: "Mongolia", code: "mn", continent: "Asia" },
    { name: "Myanmar", code: "mm", continent: "Asia" },
    { name: "Nepal", code: "np", continent: "Asia" },
    { name: "Corea del Norte", code: "kp", continent: "Asia" },
    { name: "Omán", code: "om", continent: "Asia" },
    { name: "Pakistán", code: "pk", continent: "Asia" },
    { name: "Palestina", code: "ps", continent: "Asia" },
    { name: "Filipinas", code: "ph", continent: "Asia" },
    { name: "Qatar", code: "qa", continent: "Asia" },
    { name: "Arabia Saudita", code: "sa", continent: "Asia" },
    { name: "Singapur", code: "sg", continent: "Asia" },
    { name: "Corea del Sur", code: "kr", continent: "Asia" },
    { name: "Sri Lanka", code: "lk", continent: "Asia" },
    { name: "Siria", code: "sy", continent: "Asia" },
    { name: "Taiwán", code: "tw", continent: "Asia" },
    { name: "Tayikistán", code: "tj", continent: "Asia" },
    { name: "Tailandia", code: "th", continent: "Asia" },
    { name: "Turquía", code: "tr", continent: "Asia" },
    { name: "Turkmenistán", code: "tm", continent: "Asia" },
    { name: "Emiratos Árabes Unidos", code: "ae", continent: "Asia" },
    { name: "Uzbekistán", code: "uz", continent: "Asia" },
    { name: "Vietnam", code: "vn", continent: "Asia" },
    { name: "Yemen", code: "ye", continent: "Asia" },

    // África
    { name: "Argelia", code: "dz", continent: "África" },
    { name: "Angola", code: "ao", continent: "África" },
    { name: "Benín", code: "bj", continent: "África" },
    { name: "Botsuana", code: "bw", continent: "África" },
    { name: "Burkina Faso", code: "bf", continent: "África" },
    { name: "Burundi", code: "bi", continent: "África" },
    { name: "Camerún", code: "cm", continent: "África" },
    { name: "Cabo Verde", code: "cv", continent: "África" },
    { name: "República Centroafricana", code: "cf", continent: "África" },
    { name: "Chad", code: "td", continent: "África" },
    { name: "Comoras", code: "km", continent: "África" },
    { name: "Congo (RDC)", code: "cd", continent: "África" },
    { name: "Congo (República)", code: "cg", continent: "África" },
    { name: "Yibuti", code: "dj", continent: "África" },
    { name: "Egipto", code: "eg", continent: "África" },
    { name: "Guinea Ecuatorial", code: "gq", continent: "África" },
    { name: "Eritrea", code: "er", continent: "África" },
    { name: "Esuatini", code: "sz", continent: "África" },
    { name: "Etiopía", code: "et", continent: "África" },
    { name: "Gabón", code: "ga", continent: "África" },
    { name: "Gambia", code: "gm", continent: "África" },
    { name: "Ghana", code: "gh", continent: "África" },
    { name: "Guinea", code: "gn", continent: "África" },
    { name: "Guinea-Bissau", code: "gw", continent: "África" },
    { name: "Costa de Marfil", code: "ci", continent: "África" },
    { name: "Kenia", code: "ke", continent: "África" },
    { name: "Lesoto", code: "ls", continent: "África" },
    { name: "Liberia", code: "lr", continent: "África" },
    { name: "Libia", code: "ly", continent: "África" },
    { name: "Madagascar", code: "mg", continent: "África" },
    { name: "Malaui", code: "mw", continent: "África" },
    { name: "Malí", code: "ml", continent: "África" },
    { name: "Mauritania", code: "mr", continent: "África" },
    { name: "Mauricio", code: "mu", continent: "África" },
    { name: "Marruecos", code: "ma", continent: "África" },
    { name: "Mozambique", code: "mz", continent: "África" },
    { name: "Namibia", code: "na", continent: "África" },
    { name: "Níger", code: "ne", continent: "África" },
    { name: "Nigeria", code: "ng", continent: "África" },
    { name: "Ruanda", code: "rw", continent: "África" },
    { name: "Santo Tomé y Príncipe", code: "st", continent: "África" },
    { name: "Senegal", code: "sn", continent: "África" },
    { name: "Seychelles", code: "sc", continent: "África" },
    { name: "Sierra Leona", code: "sl", continent: "África" },
    { name: "Somalia", code: "so", continent: "África" },
    { name: "Sudáfrica", code: "za", continent: "África" },
    { name: "Sudán del Sur", code: "ss", continent: "África" },
    { name: "Sudán", code: "sd", continent: "África" },
    { name: "Tanzania", code: "tz", continent: "África" },
    { name: "Togo", code: "tg", continent: "África" },
    { name: "Túnez", code: "tn", continent: "África" },
    { name: "Uganda", code: "ug", continent: "África" },
    { name: "Zambia", code: "zm", continent: "África" },
    { name: "Zimbabue", code: "zw", continent: "África" },

    // Oceanía
    { name: "Australia", code: "au", continent: "Oceanía" },
    { name: "Fiyi", code: "fj", continent: "Oceanía" },
    { name: "Kiribati", code: "ki", continent: "Oceanía" },
    { name: "Islas Marshall", code: "mh", continent: "Oceanía" },
    { name: "Micronesia", code: "fm", continent: "Oceanía" },
    { name: "Nauru", code: "nr", continent: "Oceanía" },
    { name: "Nueva Zelanda", code: "nz", continent: "Oceanía" },
    { name: "Palaos", code: "pw", continent: "Oceanía" },
    { name: "Papúa Nueva Guinea", code: "pg", continent: "Oceanía" },
    { name: "Samoa", code: "ws", continent: "Oceanía" },
    { name: "Islas Salomón", code: "sb", continent: "Oceanía" },
    { name: "Tonga", code: "to", continent: "Oceanía" },
    { name: "Tuvalu", code: "tv", continent: "Oceanía" },
    { name: "Vanuatu", code: "vu", continent: "Oceanía" }
];
